/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fiuba.algo3.modelo.interfazGrafica;

import fiuba.algo3.modelo.excepciones.NoExisteEsaPosicion;
import fiuba.algo3.modelo.juego.PuntuacionesAltas;

/**
 *
 * @author Cancel
 */
public class PantallaMaximasPuntuaciones extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMaximasPuntuaciones
     */
    public PantallaMaximasPuntuaciones() throws NoExisteEsaPosicion {
        initComponents();
        PuntuacionesAltas puntuacionesAltas = new PuntuacionesAltas();
       
        //this.jugadorMaximo1.setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloDeMaximasPuntuaciones = new javax.swing.JLabel();
        jugadorMaximo1 = new javax.swing.JLabel();
        puntajeMaximo1 = new javax.swing.JLabel();
        jugadorMaximo2 = new javax.swing.JLabel();
        puntajeMaximo2 = new javax.swing.JLabel();
        jugadorMaximo3 = new javax.swing.JLabel();
        puntajeMaximo3 = new javax.swing.JLabel();
        jugadorMaximo4 = new javax.swing.JLabel();
        puntajeMaximo4 = new javax.swing.JLabel();
        jugadorMaximo5 = new javax.swing.JLabel();
        puntajeMaximo5 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloDeMaximasPuntuaciones.setFont(new java.awt.Font("Ravie", 0, 31)); // NOI18N
        tituloDeMaximasPuntuaciones.setText("Máximas Puntuaciones");

        jugadorMaximo1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jugadorMaximo1.setText("Jugador1");

        puntajeMaximo1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        puntajeMaximo1.setText("puntaje1");

        jugadorMaximo2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jugadorMaximo2.setText("Jugador2");

        puntajeMaximo2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        puntajeMaximo2.setText("puntaje2");

        jugadorMaximo3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jugadorMaximo3.setText("Jugador3");

        puntajeMaximo3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        puntajeMaximo3.setText("puntaje3");

        jugadorMaximo4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jugadorMaximo4.setText("Jugador4");

        puntajeMaximo4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        puntajeMaximo4.setText("puntaje4");

        jugadorMaximo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jugadorMaximo5.setText("Jugador5");

        puntajeMaximo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        puntajeMaximo5.setText("puntaje5");

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(tituloDeMaximasPuntuaciones)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorMaximo5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(puntajeMaximo5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorMaximo4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(puntajeMaximo4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorMaximo3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(puntajeMaximo3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorMaximo2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(puntajeMaximo2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorMaximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(puntajeMaximo1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDeMaximasPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorMaximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeMaximo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorMaximo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeMaximo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorMaximo3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeMaximo3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorMaximo4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeMaximo4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorMaximo5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeMaximo5))
                .addGap(90, 90, 90)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        PantallaDeInicio inicio = new PantallaDeInicio();
        this.show(false);
        inicio.show();
    }//GEN-LAST:event_botonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JLabel jugadorMaximo1;
    private javax.swing.JLabel jugadorMaximo2;
    private javax.swing.JLabel jugadorMaximo3;
    private javax.swing.JLabel jugadorMaximo4;
    private javax.swing.JLabel jugadorMaximo5;
    private javax.swing.JLabel puntajeMaximo1;
    private javax.swing.JLabel puntajeMaximo2;
    private javax.swing.JLabel puntajeMaximo3;
    private javax.swing.JLabel puntajeMaximo4;
    private javax.swing.JLabel puntajeMaximo5;
    private javax.swing.JLabel tituloDeMaximasPuntuaciones;
    // End of variables declaration//GEN-END:variables
}
