package fiuba.algo3.modelo.interfazGrafica;

import fiuba.algo3.modelo.juego.Jugador;
import fiuba.algo3.modelo.juego.Puntuacion;
import javax.swing.SwingConstants;

public class PantallaJuegoTerminado extends javax.swing.JFrame {


    public PantallaJuegoTerminado(Jugador jugador, Puntuacion puntuacion) {
        initComponents();
        this.show();
        labelPuntaje.setText(jugador.getNombre());
        labelPuntaje.setText(String.valueOf(puntuacion.getPuntos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSuPuntajeEs = new javax.swing.JLabel("SU PUNTAJE ES:", SwingConstants.CENTER);
        labelPuntaje = new javax.swing.JLabel("Jugador", SwingConstants.CENTER);
        labelFelicitaciones1 = new javax.swing.JLabel("FELICITACIONES", SwingConstants.CENTER);
        labelJugador1 = new javax.swing.JLabel("Jugador", SwingConstants.CENTER);
        botonVolverAlMenuDeInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 558));
        setResizable(false);

        labelSuPuntajeEs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelSuPuntajeEs.setText("SU PUNTAJE ES:");

        labelPuntaje.setFont(new java.awt.Font("Motorwerk", 0, 90)); // NOI18N
        labelPuntaje.setText("PUNTAJE");

        labelFelicitaciones1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelFelicitaciones1.setText("FELICITACIONES");

        labelJugador1.setFont(new java.awt.Font("Motorwerk", 0, 90)); // NOI18N
        labelJugador1.setText("Jugador");

        botonVolverAlMenuDeInicio.setText("Volver a Inicio");
        botonVolverAlMenuDeInicio.setMaximumSize(new java.awt.Dimension(5000, 5000));
        botonVolverAlMenuDeInicio.setMinimumSize(new java.awt.Dimension(900, 558));
        botonVolverAlMenuDeInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAlMenuDeInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(labelSuPuntajeEs)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverAlMenuDeInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(344, Short.MAX_VALUE)
                    .addComponent(labelFelicitaciones1)
                    .addGap(308, 308, 308)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(labelSuPuntajeEs, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPuntaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(botonVolverAlMenuDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(labelFelicitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(471, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(labelJugador1)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAlMenuDeInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAlMenuDeInicioActionPerformed
        PantallaDeInicio inicio = new PantallaDeInicio();
        this.show(false);
        inicio.show();
    }//GEN-LAST:event_botonVolverAlMenuDeInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverAlMenuDeInicio;
    private javax.swing.JLabel labelFelicitaciones1;
    private javax.swing.JLabel labelJugador1;
    private javax.swing.JLabel labelPuntaje;
    private javax.swing.JLabel labelSuPuntajeEs;
    // End of variables declaration//GEN-END:variables
}
